
%Other header
a2hbc_header;

%Multiplataform database locations
if( ispc() )
    
    databases_paths = { ... 
                        'D:\Mariano\papers\ECG Classification\DB\' ... 
                        'E:\Other DBs\' ...
                        'H:\Other DBs\'; ... 
                        };
        
else
    
    databases_paths = { ...
                        '/extra/scratch/bio/mllamedo/DB/' ... 
                        '/extra/database/bio/ecg/' ...
                        };
end

DB_info =  { ...
... %Short name                Long Name                                                                          Format     #leads     #recs    #extension
    'MITBIH-AR'            ,  'MITBIH Arrhythmia Database'                                                    ,  'MIT'      , 2        , 44    , 'dat'    ; ...
    'MITBIH-SUP'           ,  'MIT-BIH Supraventricular Arrhythmia Database'                                  ,  'MIT'      , 2        , 78    , 'dat'    ; ...
    'FANTASIA'             ,  'Fantasia'                                                                      ,  'MIT'      , 2        , 1     , 'dat'    ; ...
    'AHA'                  ,  'AHA'                                                                           ,  'AHA'      , 2        , 155   , 'ecg'     ; ...
    'INCART'               ,  'St Petersburg Institute of Cardiological Technics 12-lead Arrhythmia Database' ,  'MIT'      , 12       , 75    , 'dat'    ; ...
    'ESTTDB'               ,  'European ST-T Database'                                                        ,  'MIT'      , 2        , 90    , 'dat'    ; ...
    'LTSTDB'               ,  'Long-Term ST Database'                                                         ,  'MIT'      , {2 3}    , 86    , 'dat'    ; ...
    'MITBIH-ST'            ,  'MIT-BIH ST Change Database'                                                    ,  'MIT'      , 2        , 18    , 'dat'    ; ...
    'MGH-MF'               ,  'The MGH-MF Waveform Database'                                                  ,  'MIT'      , {1 2 3}  , 1     , 'dat'    ; ...
    'MITBIH-LT'            ,  'The MIT-BIH Long Term Database'                                                ,  'MIT'      , 2        , 7     , 'dat'   ; ...
    'Biosigna'             ,  'Biosigna'                                                                      ,  'HES'      , 12       , 56    , 'hes'   ; ...
    'AMI-patients'         ,  'E-HOL-03-160-001 Acute Myocardial Infarction'                                  ,  'ISHNE'    , 3        , 1     , 'ecg'   ; ...
    'CAD-patients'         ,  'E-HOL-03-0273-002 Coronary artery patients'                                    ,  'ISHNE'    , 3        , 1     , 'ecg'   ; ...
    'Healthy-ind'          ,  'E-HOL-03-0206-003 Healthy Individuals'                                         ,  'ISHNE'    , 3        , 1     , 'ecg'   ; ...
    'qt2'                  ,  'E-HOL-12-140-008 Thorough QT Study 2'                                          ,  'ISHNE'    , 12       , 1     , 'ecg'   ; ...
    'RTDP'                 ,  'E-OTH-12-6-009 Recorded torsades de pointes event'                             ,  'ISHNE'    , 12       , 1     , 'ecg'   ; ...
    'CPTDP'                ,  'E-OTH-12-68-010 Card Pat with and without a History of Drug-induced TdP'       ,  'ISHNE'    , 12       , 1     , 'ecg'   ; ...
    'Afibp'                ,  'E-OTH-12-0073-011 AFib patients'                                               ,  'ISHNE'    , 12       , 1     , 'ecg'   ; ...
    'CPP'                  ,  'E-HOL-12-1172-012 Chest Pain Patients' 	                                      ,  'ISHNE'   , 12       , 1      , 'ecg'   ; ...
    'GCLQTS'               ,  'E-HOL-03-0480-013 Genotyped Cong LQTS'                                         ,  'ISHNE'    , 3        , 1     , 'ecg'   ; ...
    };

% DB column indexes
ShortName_idx = 1;
LongName_idx = 2;
Format_idx = 3;
Leads_idx = 4;
CantRecordings_idx = 5;
RecExtension_idx = 6;
